version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - ./requirements/nginx/tools:/etc/nginx/ssl/
      - wp-volume:/var/www
    restart: always

  mariadb:
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_HOST: "mariadb"
        WP_URL: ${WP_URL}
        WP_TITLE: ${WP_TITLE}
        WP_ADMIN_USER: ${WP_ADMIN_USER}
        WP_ADMIN_PASS: ${WP_ADMIN_PASS}
        WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - wp-volume:/var/www
    networks:
      - inception
    restart: always

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/aconciar/data/wordpress

  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/aconciar/data/mariadb

networks:
    inception:
        driver: bridge
